server:
  port: ${SERVER_PORT:9090}
  compression:
    enabled: ${ENABLE_RESPONSE_COMPRESSION:false}
    mime-types: text/xml,text/plain,text/css,application/javascript,application/x-javascript,application/rss+xml,application/xml,application/json,application/octet-stream